title = "LAILa"
description = "Lysators AI Laboratory är ett projekt inom datorföreningen Lysator som utforskar teknologier som möjliggör maskininlärning. Just nu utvecklas 'LAILa-A', ett experimentellt GPU-kluster."
default_language = "sv"
base_url = "https://test-bolmso.github.io/site/"
minify_html = true

compile_sass = true
build_search_index = false

[markdown]
external_links_target_blank = true

[slugify]
paths_keep_dates = true
